spring.application.name=groceryapi

spring.data.mongodb.uri=${MONGODB_URI}
#spring.data.mongodb.database=Groceryapp

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000

app.seller.email=${SELLER_EMAIL}
app.seller.password=${SELLER_PASSWORD}

# Cloudinary Configuration
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}

# File Upload Configuration
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Razorpay Configuration
razorpay.key-id=${RAZORPAY_KEY_ID}
razorpay.key-secret=${RAZORPAY_KEY_SECRET}

